// Build Plugins.json (consumed by PCM) from the authored sources:
//   manifest.json  — Liko's own mods (FUSAM-valid + custom PCM fields)   [also read directly by BMM/FUSAM]
//   external.json  — other authors + hotfixes (PCM-only; legacy plugins or addon schema)
//   meta.json      — updateId + changelog (cn/en)
// login.json is intentionally NOT merged here: PCM reads it independently so a broken
// login.json can never stop plugins from loading.
//
// Run after editing any source:  node scripts/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync('manifest.json', 'utf8'));
const external = JSON.parse(readFileSync('external.json', 'utf8'));
const meta     = JSON.parse(readFileSync('meta.json', 'utf8'));

// FUSAM/BMM load type -> PCM load type. 'eval' is PCM's default so we omit it.
function pcmType(fusamType) {
  if (fusamType === 'module') return 'mod';
  if (fusamType === 'script') return 'scr';
  return undefined; // 'eval' / unset -> PCM default (fetch+inject text)
}

function addonToPcm(a) {
  const stable = a.versions?.find((v) => v.distribution === 'stable') || a.versions?.[0];
  const beta   = a.versions?.find((v) => v.distribution === 'beta');
  const t = pcmType(a.type);
  return {
    id: a.id,
    name: a.name.cn,
    // Keep the image URL and emoji fallback separately. PCM displays the image
    // when available, then falls back to iemoji if the image cannot be loaded.
    ...(a.icon ? { icon: a.icon } : {}),
    iemoji: a.iemoji ?? '🐈‍⬛',
    en_name: a.name.en,
    description: a.description.cn,
    en_description: a.description.en,
    additionalInfo: a.additionalInfo?.cn ?? '',
    en_additionalInfo: a.additionalInfo?.en ?? '',
    url: stable?.source,
    ...(beta ? { altUrl: beta.source } : {}),
    ...(a.mirror?.stable ? { mirrorUrl: a.mirror.stable } : {}),
    ...(a.mirror?.beta ? { altMirrorUrl: a.mirror.beta } : {}),
    ...(a.triLabels ? { triLabels: a.triLabels } : {}),
    ...(a.website ? { website: a.website } : {}),
    priority: a.priority ?? 5,
    ...(a.version ? { version: a.version } : {}),
    ...(t ? { type: t } : {}),
  };
}

// Liko's own, minus any flagged pcmskip (published to FUSAM but hidden from the PCM list).
// pcmskip 在 manifest 一律寫布林 true（不要寫字串 "true"，否則這個 !== 比較會漏掉）。
if (!Array.isArray(manifest.addons)) {
  throw new TypeError('manifest.json must contain an "addons" array');
}

const own = manifest.addons.filter((a) => a.pcmskip !== true).map(addonToPcm);

// external.json now uses the same FUSAM-compatible { version, addons } schema
// as manifest.json. Keep accepting the former { plugins } PCM schema so older
// branches/checkouts can still be built without a hard migration boundary.
let externalPlugins;
if (Array.isArray(external.addons)) {
  externalPlugins = external.addons.filter((a) => a.pcmskip !== true).map(addonToPcm);
} else if (Array.isArray(external.plugins)) {
  externalPlugins = external.plugins;
} else {
  throw new TypeError('external.json must contain an "addons" array (or legacy "plugins" array)');
}

const duplicateIds = [...own, ...externalPlugins]
  .map((plugin) => plugin.id)
  .filter((id, index, ids) => id && ids.indexOf(id) !== index)
  .filter((id, index, ids) => ids.indexOf(id) === index);
if (duplicateIds.length) {
  throw new Error(`Duplicate plugin id(s) across manifest.json and external.json: ${duplicateIds.join(', ')}`);
}

const out = {
  _comment: 'AUTO-GENERATED by scripts/build.mjs from manifest.json + external.json + meta.json. Do NOT edit by hand — edit the sources and re-run the build.',
  updateId: meta.updateId,
  changelog: meta.changelog.cn,
  en_changelog: meta.changelog.en,
  plugins: [...own, ...externalPlugins],
};

writeFileSync('Plugins.json', JSON.stringify(out, null, 2) + '\n');
console.log(`✅ Plugins.json rebuilt — ${own.length} own + ${externalPlugins.length} external = ${out.plugins.length} plugins`);
